services:
  mcserver:
    build: .
    container_name: mcserver
    restart: unless-stopped
    environment:
      - MEMORYSIZE=8G
      - TZ=Europe/Istanbul
    ports:
      - "25565:25565/tcp"
      - "25565:25565/udp"
    volumes:
      - /data/mcserver:/data:rw
    stdin_open: true
    tty: true

